name: Update Resume PDF

on:
  push:
    paths:
      - resume.docx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install LaTeX and Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-full

      - name: Convert DOCX to PDF
        run: |
          pandoc resume.docx -o resume.pdf --pdf-engine=xelatex

      - name: Commit and Push PDF
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Auto-update resume PDF'
          branch: main
